[package]
name = "bevy_mod_aseprite"
version = "0.7.2"
edition = "2021"
description = "A plugin for using Aseprite animations in Bevy"
repository = "https://github.com/ka-de/bevy_mod_aseprite"
license = "MIT"
exclude = ["assets/"]

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = [
  "bevy_render",
  "bevy_asset",
  "bevy_sprite",
] }
bevy_aseprite_derive = "0.3"
bevy_aseprite_reader = "0.1"

[dev-dependencies]
bevy = "0.13.2"
